version: "3.4"

networks:
  go-app-network:
    driver: bridge

services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: go-app
    ports:
      - "5000:5000"
    networks:
      - go-app-network

  prometheus:
    build:
      context: .
      dockerfile: Dockerfile.prom
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - go-app-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - go-app-network

volumes:
  grafana-storage:
