version: "3.4"

networks:
  go-app-network:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    network_mode: go-app-network

  go-app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: go-app
    ports:
      - "5000:5000"
    networks:
      - go-app-network
